//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoanAppClassLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserFinancial
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UserFinancial()
        {
            this.Offers = new HashSet<Offer>();
        }
    
        public int QuoteId { get; set; }
        public int UserId { get; set; }
        public decimal Deposit { get; set; }
        public string Telephone { get; set; }
        public decimal Salary { get; set; }
        public decimal Expenses { get; set; }
        public int LoanTerm { get; set; }
        public double AffIntRate { get; set; }
        public double RpmtIntRate { get; set; }
        public decimal PurchasePrice { get; set; }
        public decimal QualifyAmount { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Offer> Offers { get; set; }
    }
}
