//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoanAppLibraryV4
{
    using System;
    using System.Collections.Generic;
    
    public partial class Offer
    {
        public int OfferId { get; set; }
        public int UserId { get; set; }
        public Nullable<int> QuoteId { get; set; }
        public Nullable<decimal> OfferAmount { get; set; }
        public Nullable<int> Term { get; set; }
        public Nullable<double> InterestRate { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public int OfferStatusId { get; set; }
        public string ProviderName { get; set; }
        public string CompanyReg { get; set; }
        public Nullable<int> UserAccept { get; set; }
    
        public virtual OfferStatu OfferStatId { get; set; }
        public virtual UserFinancial UserFinancial { get; set; }
        public virtual OfferStatu OfferStatu1 { get; set; }
    }
}
