//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoanAppLibraryV4
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserFinancial
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UserFinancial()
        {
            this.Offers = new HashSet<Offer>();
        }
    
        public int QuoteId { get; set; }
        public int UserId { get; set; }
        public Nullable<int> LoanTerm { get; set; }
        public Nullable<double> AffIntRate { get; set; }
        public Nullable<decimal> PurchasePrice { get; set; }
        public Nullable<decimal> Deposit { get; set; }
        public Nullable<decimal> QualifyAmount { get; set; }
        public Nullable<decimal> Salary { get; set; }
        public Nullable<decimal> Expenses { get; set; }
        public Nullable<decimal> MonthlyRepayment { get; set; }
        public Nullable<decimal> TotalDueInclInterest { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Offer> Offers { get; set; }
    }
}
