//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBClassEFLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User()
        {
            this.Logs = new HashSet<Log>();
        }
    
        public int UserId { get; set; }
        public int LevelId { get; set; }
        public string Password { get; set; }
        public string First_name { get; set; }
        public string Last_name_ { get; set; }
        public string Address_line_1 { get; set; }
        public string Address_line_2 { get; set; }
        public string City { get; set; }
        public string Post_code { get; set; }
        public string Telephone { get; set; }
        public string Email { get; set; }
        public string Provider_name { get; set; }
        public string Company_reg { get; set; }
        public string Username { get; set; }
    
        public virtual AccessLevel AccessLevel { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Log> Logs { get; set; }
    }
}
