//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoanAppLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class Offer
    {
        public int OfferId { get; set; }
        public int UserId { get; set; }
        public int QuoteId { get; set; }
        public decimal Offer_Amount { get; set; }
        public int Term { get; set; }
        public double Interest_Rate { get; set; }
        public string First_Name { get; set; }
        public string Last_Name { get; set; }
        public System.DateTime Date { get; set; }
        public string Offer_Status { get; set; }
        public string Provider_Name { get; set; }
        public string Company_Reg { get; set; }
    
        public virtual UserFinancial UserFinancial { get; set; }
    }
}
